(cl:defpackage ar_recog-srv
  (:use )
  (:export
   "CALIBRATEDISTANCE"
   "<CALIBRATEDISTANCE-REQUEST>"
   "CALIBRATEDISTANCE-REQUEST"
   "<CALIBRATEDISTANCE-RESPONSE>"
   "CALIBRATEDISTANCE-RESPONSE"
  ))

